### ISSUE TITLE
Early / Older PowerMax Panels not connecting (Plus and Pro)

### ISSUE THREAD

**Issue by davesmeghead** [davesmeghead/visonic#199]
> Hello, since version 12.0.0.0 (1) the connection with my PowermaxPlus is not established anymore. When i roll back to 9.9.9.9 its working again.
> 
> [home-assistant_visonic_2025-07-07T14-42-33.930Z.zip](https://github.com/user-attachments/files/21105082/home-assistant_visonic_2025-07-07T14-42-33.930Z.zip)
> 
> I know there are other errors with missing sensors. U just moved to a other house so there is a lot changed.  

 _Originally posted by @AndreTzerra in [#197](https://github.com/davesmeghead/visonic/issues/197#issuecomment-3045507701)_

Moved to a new issue

**Comment by AndreTzerra** [comment]
Hello David,

Sorry for the last 'messy' log post.

I have installed the latest version 0.12.0.1
Restarted HA, deleted the Integration from the Integrations Dashboard.

Set the logger to:
logger:
  default: critical
  logs:
    custom_components.visonic: debug

Restarted HA and re-created the intergration.

After entering the USB port ect. I started a new log for about 10 minutes.
It seems there's no connection established.

[home-assistant_visonic_2025-07-07T16-32-50.395Z.zip](https://github.com/user-attachments/files/21106826/home-assistant_visonic_2025-07-07T16-32-50.395Z.zip)

Later in the evening I will go back to version 0.9.9.9 so that the intergation will work for now.

André

**Comment by berg78** [comment]
I have the same problem, after the update my old powermax panel is not connecting anymore.
Going to try to roll back the previous version.

**Comment by bartbakels** [comment]
My powermax pro is working when setup (clean setup) in standard mode. But when powelink mode is selected i only get my sensors but not the panel it self. Triend manual enrolling

**Comment by AndreTzerra** [comment]
Hi,

Sure. I definitely want to try it.

**Comment by davesmeghead** [comment]
I'm trying to collate what I think is the same problem in to this 1 issue.

All log files that I've seen from you all have "Access Denied" responses from the panel when I ask for the panel details. This can only be because of 3 things: 
- The download code (which is part of the "Trigger Panel Data From Panel" command)
- The time between me sending data to the panel (perhaps it's too quick and the earlier panels can't handle it i.e. their cpu is too slow)
- The earlier panels don't like the STOP command to the panel.  I already know that earlier panels do not like the INIT command but that causes lots more problems that were easier to spot.

So in both 0.9.9.9 and 0.12.0.1 I send 3 commands to the panel and wait for the panel to send the panel details. This is an example from a PowerMax Complete Panel (this is what should happen and works).

```
11:07:00.400 [sendPdu] Sent Command (Exit)    raw data 0d 0f f0 0a   waiting for message response []
11:07:02.094 [sendPdu] Sent Command (Stop)    raw data 0d 0b f4 0a   waiting for message response []
11:07:03.596 [sendPdu] Sent Command (Trigger Panel Data From Panel)    raw data 0d 24 00 00 56 50 00 00 00 00 00 00 35 0a   waiting for message response ['0X3C']
11:07:03.658 [processReceivedMessage] Received Panel Info   raw data 0d 3c fd 0a 00 00 4f 05 01 00 01 00 65 0a          response list []
11:07:03.658 [_processReceivedPacket] processAB=True processB0=False processNormalData=False    self.pmDownloadMode=False
11:07:03.659 [handle_msgtype3C] PanelType=5 : PowerMax Complete Part , Model=79   Powermaster False
```
This is what I see from one of your log files
```
18:13:06.734 [sendPdu] Sent Command (Exit)    waiting for message response []
18:13:08.234 [sendPdu] Sent Command (Stop)    waiting for message response []
18:13:09.735 [sendPdu] Sent Command (Trigger Panel Data From Panel)    waiting for message response ['0X3C']
18:13:09.759 [_processReceivedPacket] processAB=True processB0=False processNormalData=False    self.pmDownloadMode=False
18:13:09.775 [processReceivedMessage] Received Access Denied   raw data 08 f7 0a          response list ['0X3C']
18:13:09.775 [_processReceivedPacket] processAB=True processB0=False processNormalData=False    self.pmDownloadMode=False
18:13:09.776 [handle_msgtype08] Access Denied  len 0 data 
18:13:10.732 [_sequencer] SeqState=WaitingForPanelDetails     Counter=4      PanelMode=STOPPED     PanelState=['UNKNOWN', 'UNKNOWN', 'UNKNOWN']     SendQueue=0
18:13:10.732 [_sequencer] Access Denied
18:13:10.732 [_sequencer]     AccessDenied last command 24 00 00
18:13:10.732 [_sequencer]           Got an Access Denied and we have sent a Bump or a Download command to the Panel
18:13:10.732 [_sequencer]    Moved on to next download code and going to init
```

I'm assuming that it's the download code that's the problem and I think that's where I'd like to start investigating.

**Comment by AndreTzerra** [comment]
Your explanation is making sence. I already saw the 'Access Denied'.

Because I am pretty sure that I use the right download code, It indeed must be something in the way the proces is handled.
I will give it a try and let you know!

**Comment by davesmeghead** [comment]
The 2 files in the zip file will use download code 5650 by default, unless you set the "EPROM download code" in the configuration, in which case it should use that.  Other later panels (especially PowerMaster) use AAAA by default. Because your panels are older they should use 5650 by default.

Do you override the download code?

**Comment by AndreTzerra** [comment]
I use an own override download code.  It always works.

Im still bilding the log for about 5 minutes, but I can tell you that it connects for now. 
 I see the sensors reacting, but I do not have an Powermax status on the right. 

<img width="1046" height="721" alt="Image" src="https://github.com/user-attachments/assets/66478897-7042-42c4-9c6a-158fde3fcfab" />

I send the log in a moment.

**Comment by AndreTzerra** [comment]
After replacing pyvisonic en a restart:

Armed en Disarmed as you asked for.

[home-assistant_visonic_2025-07-08T17-07-06.425Z.zip](https://github.com/user-attachments/files/21126579/home-assistant_visonic_2025-07-08T17-07-06.425Z.zip)

**Comment by davesmeghead** [comment]
Just a quick question, do you have any X10 devices, your panel says you have 15: X01 to X15

**Comment by davesmeghead** [comment]
I still can't work out why you need to enter the usercode to arm and disarm as you get to Powerlink emulation mode, the only reason that I can think of is that you accidentally ticked the force keypad config setting.  I've done a few fixes, merged back in the PowerMaster capabilities and added a bit of logging for arm/disarm

Can you give this a test please and create a log file, thanks
[visonic.zip](https://github.com/user-attachments/files/21131730/visonic.zip)

**Comment by davesmeghead** [comment]
Thanks for the log files, they are very much appreciated.

> I just dont see the panel status, and the last event.

This is in the release notes, I've changed some of the Entity attributes so you'll need to update them in the frontend.  e.g. emulationmode is the attribute that gives you the connection mode i.e. Standard, Powerlink etc.  The last event data has also changed.

I suggest that you use "developer tools" in HA, select "states" from the top and filter on "visonic", find your `alarm_control_panel.visonic_alarm` Entity. This is my test panel Entity as an example for you, but this has partitions which you don't so take a look at your own, I hope this helps though.

<img width="912" height="907" alt="Image" src="https://github.com/user-attachments/assets/9cdf7d7c-55da-405b-9c90-ad1333b40a87" />

**Comment by AndreTzerra** [comment]
I Hi,

I completely missed that one.
I have updated 'mode' to 'emulationmode' and for the last event into 'lasteventaction' in the frontend.

**Comment by davesmeghead** [comment]
Do you consider this Issue as resolved or is there anything else?  
What about the other contributors to this Issue, do you wish to test before I create a new HACS formal release?

**Comment by AndreTzerra** [comment]
For me, as far as I can see the Issue is resolved.

Thank you for the fast help. 
I really appreciate it.

**Comment by berg78** [comment]
Thanks for the great work guys. I didn't have time to test it myself

I am going to install the new update files tonight. But as far is a i can read here it looks like the issue is solved, so you can close it.
If i doesn't work i will come back here.

Thanks Dave for the great add-in and Andre for testing :-)

**Comment by herwinjan** [comment]
Hi,

I also issue's with my PowerMax Pro. 
I cant get it to enroll! I tried Emulation Mode, but then it got stuck on WaitingForEnrolSuccess.
Standard mode is a bit working, i can see my sensors.

BTW i also miss Zone 10, it is not shown in HA.

I use the latest code from above and attached the log from the latest reload. 
When askes in de logs, i enrolled the PowerMax, but did not work!


Thanks!


[home-assistant_visonic_2025-07-10T09-12-04.945Z.log.zip](https://github.com/user-attachments/files/21159667/home-assistant_visonic_2025-07-10T09-12-04.945Z.log.zip)

**Comment by davesmeghead** [comment]
@herwinjan 
You get to Standard Plus and seem to enter Installer mode on the panel where I assume that you do the manual enrol.  You then need to exit installer mode on the panel, please try exiting Installer on the panel after you manually enrol. Also, it can take a while for the panel to send out the enrol request. You're looking for this "Panel wants to auto-enrol" in the log file when the panel asks to Enrol.

@bartbakels 
I need a proper HA log file and not just the diagnostics file.  Please see [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) on the wiki.

Can you both try these files
[visonic.zip](https://github.com/user-attachments/files/21161827/visonic.zip)

**Comment by herwinjan** [comment]
@davesmeghead Tested again with your new version. same as @bartbakels.

Still got: 2025-07-10 14:34:19.349 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [processReceivedMessage] Received Unknown F1   raw data f1 07 43          response list []
2025-07-10 14:34:19.350 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [_processReceivedPacket] processAB=True processB0=True processNormalData=True    self.pmDownloadMode=False
2025-07-10 14:34:19.350 DEBUG (MainThread) [custom_components.visonic.pyvisonic] [_processReceivedPacket] Unknown/Unhandled packet type 0d f1 07 43 00 00 8b 56 0a

when i enroll.

**Comment by bartbakels** [comment]
> > Also i would expect a fallback to normal mode, and the panel to be created. but its not there.
> 
> I agree, and after testing it doesn't. So I've created a test for you to try, this also tries to coerce the panel in to enroling better, but over a longer period of time while in standard plus emulation mode (although you will still need to try to manually enrol).
> 
> Can you also try to use the menus on the panel to tell it that the powerlink module has been removed from the panel and then after restarting HA, try to manually enrol.
> 
> [visonic.zip](https://github.com/user-attachments/files/21190969/visonic.zip)

Tested this one, and the panel is going to standard plus and is created. However enrolling is still not working, but i am not sure if i got this managed before..? send several times a register powerlink command but not luck see logs. However the panel is working now.

[home-assistant.zip](https://github.com/user-attachments/files/21194983/home-assistant.zip)

**Comment by herwinjan** [comment]
@davesmeghead  Thanks, i will try monday!
How do i remove the Powerlink Module in the Menu?

**Comment by bartbakels** [comment]
> [@davesmeghead](https://github.com/davesmeghead) Thanks, i will try monday! How do i remove the Powerlink Module in the Menu?

Not sure, i have 2 options in the powerlink menu (teanzlated from dutch)

Enroll
Fault (on or off)

Bart

**Comment by davesmeghead** [comment]
I've just created a HACS Release 0.12.1.0 with the code changes to date. 
Please install the latest release for any further posts in to this Issue.

**Comment by bartbakels** [comment]
hmm, strange that i dont get the sensor information, i got before, which sensor is what etc, and also i dont get the numerical disarm panel anymore (tried both settings)

btw enrolling powerlink does it need a specific wiring? (DTR DSR etc?)

**Comment by phoenix-blue** [comment]
> > Also i would expect a fallback to normal mode, and the panel to be created. but its not there.
> 
> I agree, and after testing it doesn't. So I've created a test for you to try, this also tries to coerce the panel in to enroling better, but over a longer period of time while in standard plus emulation mode (although you will still need to try to manually enrol).
> 
> Can you also try to use the menus on the panel to tell it that the powerlink module has been removed from the panel and then after restarting HA, try to manually enrol.
> 
> [visonic.zip](https://github.com/user-attachments/files/21190969/visonic.zip)

Hello,

I have also manual update the files, at this side it's also back online (Powermax Pro).
Thx

**Comment by herwinjan** [comment]
@davesmeghead my panel was confused i think. Powered off the panel and relearned Zone 10 and now everything is working as expected. No manual enrollement was necessary.

Thanks for your time and efford!

**Comment by haforme** [comment]
Dave, just wanted to let you know that the latest version 0.12.1.0 has fixed the issues with connecting to my PowerMax Plus.  A second alarm entity was not created like it was previously and the upgrade worked perfectly.  I also upgraded another Home Assistant that connects to the PowerMax Pro with no issues.  Thanks again for your development work.

**Comment by davesmeghead** [comment]
@bartbakels 
> its working however cant get powerlink enrolled and stay in standard-plus, any tips,.

When in Standard Plus, the panel and the integration are not _Enrolled_ with each other, they are not exchanging "I'm Alive" messages. This means that any timeouts the integration has for not receiving messages from the panel may be triggered and it's a gamble.  How long do I wait for the panel to send some data before declaring that the connection is broken, if I wait too long then HA does not show the true panel state, too short and it goes from standard-plus down to standard emulation mode too quickly.
In fact, when in Standard Plus I send I'm Alive messages anyway, just in case it helps. But I do not know whether the panel uses them or discards them.

When in Powerlink emulation mode the panel and integration are _Enrolled_ with each other.  They have to send "I'm Alive" messages to each other. For example, if I do not send an I'm Alive message every 15 to 25 seconds (depends on panel type) then the panel declares "Powerlink Comms Failure" as a General Trouble.

> btw enrolling powerlink does it need a specific wiring? (DTR DSR etc?)

No.

**Comment by davesmeghead** [comment]
I'll close this issue as resolved
