### ISSUE TITLE
Powermax Complete no longer connecting to panel.  Worked for years and did a fresh install of HA.

### ISSUE THREAD

**Issue by MonkeyJug** [davesmeghead/visonic#223]
I can't get the panel to connect.  It appears to connect and download all the data, but then it gives the following error.  I've installed the integration 20 times in the last 5 or so years and never had a problem.  I'm running v2025.11 if that makes in differnece?

Here's part of the log:

[home-assistant.log](https://github.com/user-attachments/files/23863483/home-assistant.log)

**Comment by davesmeghead** [comment]
I just can't work out what your panel is doing. Put back the latest release of the integration and then can you try:
- Deleting the download code and leaving it blank, restart HA and let me know what happens
- Set the download code to something else such as AAAA, restart HA and let me know what happens
- Finally, disable the integration from within HA and leave it 24 hours, then enable the integration and let me know what happens

**Comment by davesmeghead** [comment]
So what I tried didn't work, I tried to kick the panel out of the download state but it just won't.

The message `Attempt to send a command message to the panel that has been denied, wrong pin code used` is not correct, I have fixed that for the next release so just ignore it.

The message `[_sequencer] SeqState=EPROMExitDownload     Counter=1      PanelMode=STANDARD_PLUS     PanelState=['DOWNLOADING', 'UNKNOWN', 'UNKNOWN']` is the most relevant.

The sequencer is trying to exit the download panel state but your panel is ignoring the command, and responding with Access Denied.  I've never seen this before.  So I added code that sends a download exit command when it gets Access Denied,  but it looks like your panel just ignores it.  

I know you're not at home but I'd be interested to know what the text is on the front of the panel. Is it "Downloading"?

**Comment by davesmeghead** [comment]
That helps actually.
Are you able to edit the python code?  The file is `/config/custom_components/visonic/pyvisonic.py`
In release 0.12.4.4 it's line 2513.
Can you duplicate the line and change EXIT to STOP
Before
```
                                self._addMessageToSendList(Send.EXIT, priority = MessagePriority.URGENT)
```
After
```
                                self._addMessageToSendList(Send.EXIT, priority = MessagePriority.URGENT)
                                self._addMessageToSendList(Send.STOP, priority = MessagePriority.URGENT)
```

**Comment by davesmeghead** [comment]
OK fair enough
Just 1 more thought and then I'll wait until you do a reset. Add a new row with Send.INIT

```
                                self._addMessageToSendList(Send.EXIT, priority = MessagePriority.URGENT)
                                self._addMessageToSendList(Send.STOP, priority = MessagePriority.URGENT)
                                self._addMessageToSendList(Send.INIT, priority = MessagePriority.URGENT)
```
This should re-initialise the panel software, you will **not** lose anything in your panel settings so don't worry.

**Comment by MonkeyJug** [comment]
[home-assistant.log](https://github.com/user-attachments/files/23972240/home-assistant.log)

still the same mate... :(

**Comment by davesmeghead** [comment]
There's not an INIT command sent to the panel, did you save the file and restart HA?

**Comment by davesmeghead** [comment]
Hi,
The PowerMaster panels are much more critical about the download code, the PowerMax are more "flexible" about it.
About the 4 log files:
- The Random log file just fails completely (as it should do, this is the correct behaviour)
- The 5650 and AAAA work the same
- For the Blank log file, I use 5650 as a default for PowerMax panels anyway, see lines 291 to 293 in pyvisonic.py so it works the same

If you uncomment lines 3694 and 3695 in pyvisonic.py (remove the hash but don't replace it with anything like a space so it's at the same indentation level as the code above and below), it will print to the log file and create a log warning in HA for your Installer code and Download code as defined in the panels EPROM.  I suspect that it will tell you that the download code is 5650

Lastly, I have no idea what the panel is doing!
When sending an INIT to the panel it restarts its software internally, a kind of soft reset on the panel so it's in a known state to start communicating (although early PowerMax panels don't support INIT). Except that your doesn't, and I don't know why.  EXIT should exit the downloading state, STOP should tell the panel to stop what its doing and listen.  None of them seemed to work, your panel ignored EXIT and STOP, although it acknowledged each message so I know that the panel received it and accepted it. INIT was rejected with Access Denied and simple commands like get status (A5) was rejected with Access Denied.

Let me know if I can do anything else but I'm stuck at the moment.

**Comment by MonkeyJug** [comment]
I did a factory reset on my panel today, but it still throws the exact same error.

**Comment by davesmeghead** [comment]
Somewhere between release 0.12.4.2 and 0.12.4.5 the configuration data in Home Assistant (HA) became corrupted, it's my fault it happened and not the HA releases. Even if you subsequently installed an earlier version, once corrupted it would retain the corrupted values. This is the only thing that I've thought of that might be the cause.

So can you, in this order:
- Go to the Integrations page, select the integration and from the 3 vertical dots, download the diagnostics in case you can't remember your settings, although it does redact some information, it might help you to install it again later down these bullets
- Delete the hub from within HA, again from the Integrations page, select the 3 vertical dots and then delete the hub
- Install the latest release 0.12.4.7 from Github, it's a HACS release if this helps.
- Make sure you have the [debug setting correct](https://github.com/davesmeghead/visonic/wiki#logger-settings) in `configuration.yaml` to capture a log file.
- Restart HA
- Recreate the hub and allow it time to connect, let's say up to 10 minutes
- Drag and drop the captured log file `home-assistant.log` in to this issue. It has been pointed out to me that supervised installs of HA do not put the `home-assistant.log` file in /config anymore so you might need to look for it.

EDIT: I forgot to ask, did you uncomment lines 3694 and 3695 in pyvisonic.py?   DO NOT UPLOAD THIS LOG FILE as it contains your download code and installer code, but it will tell you what the panel thinks it's download code is.

**Comment by samsam-rolon** [comment]
> Hello I have the same issue there ... what should I provide for logs ?

Hello
I don't know why, it's working again since 2 days !

**Comment by davesmeghead** [comment]
OK, thanks for the information and for letting us know.

**Comment by MonkeyJug** [comment]
tried fresh install - no joy.  also tried the fixes 6 posts up, including removing (and saving) the reference in core.config_entities

i think my panel is borked.  i did change the battery pack a few months ago, before realising it was the power supply that was faulty, so replaced that also.  the alarm itself seems to be working fine, just not via the integration.

one other thing, is i recently moved the esphome addon from HA to my dedicated server using docker for esphome.  that can't be the reason though as it still updates the esp board fine from my server...

i dunno what to do now mate.

**Comment by MonkeyJug** [comment]
So I bought a new (used) panel on eBay and it connected first time.  Seems like the main board got frazzled at some point.
